# Generated by Django 5.2 on 2025-04-29 06:14

import CarDekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0003_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[CarDekho_app.models.alphanumberic]),
        ),
    ]
